"""empty message

Revision ID: 1f8f5e3231ac
Revises: 
Create Date: 2021-12-08 15:00:10.916481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8f5e3231ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('genre_name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('genre_name')
    )
    op.create_table('genres',
    sa.Column('genre_name', sa.String(length=25), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['genre_name'], ['genre.genre_name'], ),
    sa.PrimaryKeyConstraint('genre_name', 'book_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genres')
    op.drop_table('genre')
    # ### end Alembic commands ###
