"""empty message

Revision ID: c4e95f5f9456
Revises: 
Create Date: 2021-12-08 11:40:59.889398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e95f5f9456'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('timing', sa.String(length=120), nullable=False),
    sa.Column('person_email', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['person_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check')
    # ### end Alembic commands ###
