"""Initial migration.

Revision ID: 41551521e4c6
Revises: fe2e10aa25c2
Create Date: 2021-12-01 12:36:40.904271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41551521e4c6'
down_revision = 'fe2e10aa25c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
