"""Initial migration.

Revision ID: 694aef94606b
Revises: 5bfc541ba4e8
Create Date: 2021-12-08 11:24:36.395252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694aef94606b'
down_revision = '5bfc541ba4e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check', sa.Column('person_email', sa.String(), nullable=False))
    op.create_foreign_key(None, 'check', 'user', ['person_email'], ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'check', type_='foreignkey')
    op.drop_column('check', 'person_email')
    # ### end Alembic commands ###
