"""empty message

Revision ID: f2dc10f82de6
Revises: 694aef94606b
Create Date: 2021-12-08 11:29:48.523736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2dc10f82de6'
down_revision = '694aef94606b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check', sa.Column('person_email', sa.String(length=25), nullable=False))
    op.create_foreign_key(None, 'check', 'user', ['person_email'], ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'check', type_='foreignkey')
    op.drop_column('check', 'person_email')
    # ### end Alembic commands ###
