"""empty message

Revision ID: 80ce662f7c46
Revises: 
Create Date: 2021-12-08 15:54:08.110513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80ce662f7c46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'author_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('book', 'sequel_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'sequel_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('book', 'author_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
