"""empty message

Revision ID: 0c400129a861
Revises: 69a3b25df0bd
Create Date: 2021-12-20 14:15:31.528980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c400129a861'
down_revision = '69a3b25df0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('datecommented', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'datecommented')
    # ### end Alembic commands ###
